# Generated by Django 6.0.2 on 2026-03-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('location', models.CharField(max_length=200, verbose_name='Ubicación (Sala/Auditorio)')),
                ('event_date', models.DateField(verbose_name='Fecha del evento')),
                ('event_time', models.TimeField(verbose_name='Hora del evento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['event_date', 'event_time'],
            },
        ),
    ]
