# Generated by Django 5.2.14 on 2026-05-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedbed',
            name='description',
            field=models.TextField(blank=True, default='Descripción no disponible aún.'),
        ),
        migrations.AlterField(
            model_name='seedbed',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='seedbed',
            name='tutor',
            field=models.CharField(blank=True, default='Por definir', max_length=200),
        ),
    ]
